GRANT SELECT, REFERENCES ON Department
TO aheller;

GRANT SELECT, REFERENCES ON Wing
TO aheller;

GRANT SELECT, REFERENCES ON Department
TO silon;

GRANT SELECT, REFERENCES ON Wing
TO silon;

GRANT SELECT, REFERENCES ON Worker
TO yyohanan;
